// <auto-generated />
using System;
using CodeJudge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeJudge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CodeJudgeDbContext))]
    [Migration("20260904104723_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeJudge.Domain.Entities.EvaluationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<string>("Output")
                        .HasColumnType("jsonb")
                        .HasColumnName("output");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<string>("RubricItem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rubric_item");

                    b.Property<bool>("Skipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("skipped");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<int?>("TestsPassed")
                        .HasColumnType("integer")
                        .HasColumnName("tests_passed");

                    b.Property<int?>("TestsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("tests_total");

                    b.HasKey("Id")
                        .HasName("pk_evaluation_results");

                    b.HasIndex("SubmissionId", "RubricItem")
                        .IsUnique()
                        .HasDatabaseName("ux_evaluation_results_submission_rubric");

                    b.ToTable("evaluation_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_evaluation_results_rubric_item", "rubric_item IN ('Security','Compiles','Test')");

                            t.HasCheckConstraint("ck_evaluation_results_tests_count", "tests_passed IS NULL OR tests_total IS NULL OR tests_passed <= tests_total");
                        });
                });

            modelBuilder.Entity("CodeJudge.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("locked_by");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("locked_until");

                    b.Property<string>("ProblemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("problem_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_submissions");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_submissions_user_id_created_at");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("UserId", "CreatedAt"), new[] { "ProblemId", "Language", "Status" });

                    b.HasIndex("Status", "LockedUntil", "CreatedAt")
                        .HasDatabaseName("ix_submissions_queue")
                        .HasFilter("status IN ('Pending','Evaluating')");

                    b.ToTable("submissions", null, t =>
                        {
                            t.HasCheckConstraint("ck_submissions_language", "language IN ('CSharp','Python','JavaScript')");

                            t.HasCheckConstraint("ck_submissions_status", "status IN ('Pending','Evaluating','Completed','Error')");
                        });
                });

            modelBuilder.Entity("CodeJudge.Domain.Entities.EvaluationResult", b =>
                {
                    b.HasOne("CodeJudge.Domain.Entities.Submission", null)
                        .WithMany("Results")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evaluation_results_submissions_submission_id");
                });

            modelBuilder.Entity("CodeJudge.Domain.Entities.Submission", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
